### PR TITLE
Add Ubuntu 24.04 support

### PR DESCRIPTION
**Pull request by ekohl**
Normally I prefer the title to describe in a bit more detail, but it's hard to capture all while being readable.

### CODE REVIEW

**Review by smortex — APPROVED** [review]
Looks good, I would just change the PR title to something like "Refresh the list of supported operating systems" because the PR not only remove OS, but also add a bunch of new ones.

**Comment by zilchms** [comment]
In my opinion we should split this PR up, if only to have a somewhat nice changelog :)

**Comment by bastelfreak** [comment]
cherry-picked into https://github.com/voxpupuli/puppet-openssl/pull/210, https://github.com/voxpupuli/puppet-openssl/pull/211, https://github.com/voxpupuli/puppet-openssl/pull/212

**Comment by bastelfreak** [comment]
contains #191

**Pull request merged**
