### PR TITLE
Use private_key parameter when creating certificate

### LINKED ISSUE #185: [Bug] TLS certificate can't be created if the directory for private key is specified
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.28.0
- Ruby: 2.7.8
- Distribution: Rocky Linux 8.9
- Module version: 3.1.0

## How to reproduce (e.g Puppet code you use)

Try to create self-signed certificate with parameter `key_dir`, for example:

```puppet
openssl::certificate::x509 { $facts[networking][fqdn]:
    country      => 'DK',
    state        => 'Denmark',
    locality     => 'Test',
    commonname   => $facts[networking][fqdn],
    organization => 'company A/S',
    unit         => 'test',
    email        => 'admin@test.dk',
    days         => 3650,
    base_dir     => '/etc/ssl/certs',
    key_dir      => '/etc/ssl/private',
    force        => false,
    encrypted    => false,
  }
```

## What are you seeing

X509_cert is trying to use default key from the same directory with the request and certificate (`/etc/ssl/certs`). The key is generated in correct directory (`/etc/ssl/private`)

## What behaviour did you expect instead

X509_cert must use the signing key from the parameter `key_dir` (`/etc/ssl/private`)

## Output log

```
Notice: /Stage[main]/Profile::Test::Tls_certs/Openssl::Certificate::X509[host.test.dk]/Openssl::Config[/etc/ssl/certs//host.test.dk.cnf]/File[/etc/ssl/certs//host.test.dk.cnf]/content: content changed '{sha256}8447bb6632d45d40a3eaaceca9aa4cb6adf9aa98998dd463dc65d871b7db6b16' to '{sha256}dee758d609833006021578ebcf715e888c964d1ff047674445be789bc98ebae0'
Info: Openssl::Config[/etc/ssl/certs//host.test.dk.cnf]: Scheduling refresh of X509_request[/etc/ssl/certs//host.test.dk.csr]
Notice: /Stage[main]/Profile::Test::Tls_certs/Openssl::Certificate::X509[host.test.dk]/X509_request[/etc/ssl/certs//host.test.dk.csr]: Triggered 'refresh' from 1 event
Info: /Stage[main]/Profile::Test::Tls_certs/Openssl::Certificate::X509[host.test.dk]/X509_request[/etc/ssl/certs//host.test.dk.csr]: Scheduling refresh of X509_cert[/etc/ssl/certs//host.test.dk.crt]
Error: /Stage[main]/Profile::Test::Tls_certs/Openssl::Certificate::X509[host.test.dk]/X509_cert[/etc/ssl/certs//host.test.dk.crt]: Could not evaluate: No such file or directory @ rb_sysopen - /etc/ssl/certs/host.test.dk.key
Error: /Stage[main]/Profile::Test::Tls_certs/Openssl::Certificate::X509[host.test.dk]/X509_cert[/etc/ssl/certs//host.test.dk.crt]: Failed to call refresh: Execution of '/bin/openssl x509 -req -days 3650 -in /etc/ssl/certs//host.test.dk.csr -out /etc/ssl/certs//host.test.dk.crt -signkey /etc/ssl/certs/host.test.dk.key -extensions v3_req' returned 1: Signature ok
subject=/C=DK/ST=Denmark/L=Test/O=company A/S/OU=test/CN=host.test.dk/emailAddress=admin@test.dk
Getting Private key
Error opening Private key /etc/ssl/certs/host.test.dk.key
139684502910864:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('/etc/ssl/certs/host.test.dk.key','r')
139684502910864:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
unable to load Private key
unable to write 'random state'
Error: /Stage[main]/Profile::Test::Tls_certs/Openssl::Certificate::X509[host.test.dk]/X509_cert[/etc/ssl/certs//host.test.dk.crt]: Execution of '/bin/openssl x509 -req -days 3650 -in /etc/ssl/certs//host.test.dk.csr -out /etc/ssl/certs//host.test.dk.crt -signkey /etc/ssl/certs/host.test.dk.key -extensions v3_req' returned 1: Signature ok
subject=/C=DK/ST=Denmark/L=Test/O=company A/S/OU=test/CN=host.test.dk/emailAddress=admin@test.dk
Getting Private key
Error opening Private key /etc/ssl/certs/host.test.dk.key
139684502910864:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('/etc/ssl/certs/host.test.dk.key','r')
139684502910864:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
unable to load Private key
unable to write 'random state'
Notice: /Stage[main]/Profile::Test::Tls_certs/Openssl::Certificate::X509[host.test.dk]/File[/etc/ssl/certs//host.test.dk.crt]: Dependency X509_cert[/etc/ssl/certs//host.test.dk.crt] has failures: true
```

## Any additional information you'd like to impart

Commit a8a98cfa494e1945f798a3d34445826686e26575 broke the behavior.

### PR DESCRIPTION
**Pull request by vasilevalex**
#### Pull Request (PR) description
Use private key created before, not the default value.

#### This Pull Request (PR) fixes the following issues
Fixes #185

### CODE REVIEW

**Comment by zilchms** [comment]
I am still not sure if we want to allow direct private key passing into the certificate. CSRs exist for exactly this reason. The regression for no longer allowing directly passing keys into certs and using CSRs instead was made specifically for this reason.

To be clear: I am not against allowing passing the private key directly, I just would like to get a good reason to do so

I may also be completely wrong here, been a while since I made those changes

**Comment by TheMeier** [comment]
@zilchms the point here is not that the user passes a key, but that the path to the key created before by `x509_request` is used.

**Comment by vasilevalex** [comment]
In the simplest case without CA we need some private key to sign the certificate. So openssl is invokeg with -signkey:
https://github.com/voxpupuli/puppet-openssl/blob/dcd89b5b529a2ab1f74c8b4869d8ba2a155131ca/lib/puppet/provider/x509_cert/openssl.rb#L84
with the private key as parameter. And if we don't pass the private key generated earlier, default value would be used.

**Comment by fmichea** [comment]
> From @zilchms : I am still not sure if we want to allow direct private key passing into the certificate. CSRs exist for exactly this reason. The regression for no longer allowing directly passing keys into certs and using CSRs instead was made specifically for this reason.

Just hit this issue as well, I'm a bit of two minds on this. On one hand this bug currently prevents using the ``key``/``csr``/``cert`` parameters in order to control their naming convention. Plus if these parameters are not used, then the key is indeed passed to the certificate for signing anyway, with the correct name this time so no failure happens. So in the current state of things it doesn't appear to me that this fix should necessarily be blocked short term.

On the other hand I take your point about CSR, and for those that use a CA to then sign the certificates, maybe the right solution would be to allow creating the CNF + KEY + CSR without the certificate, and let that be generated by the CA?

At least in my setup I am working on, I get the certificate because its generated by default, but I dont use it and instead create signed versions from the CSR and my CA to then be uploaded. I could totally use an option to turn of cert generation off since those files are not necessary to me.

Any thoughts?

**Comment by yakatz** [comment]
It looks like the PR needs a rebased. Running through the comments very quickly, I don't see any objections, so once it can be cleanly merged, we should be able to do so.

**Comment by yakatz** [comment]
Actually, @zilchms might be opposed. Can you clarify?

**Comment by zilchms** [comment]
No further objections, feel free to merge after rebasing and passing CI :) At some point I will write some tests and refactor a bit of this module, so bugs/regressions like this dont sneak in unnoticed/without discussion beforehand

**Comment by vasilevalex** [comment]
Rebased and passed CI

**Comment by ekohl** [comment]
@vasilevalex sorry, but we've been working on this module today and that introduced another merge conflict. Good news is that we should have acceptance tests now so it should be easier to add an acceptance test to it.

**Comment by ekohl** [comment]
I took the liberty to rebase your PR.

**Pull request merged**
