### PR TITLE
Fix variable (#100) and revamp cert template to accept IPs (#98)

### PR DESCRIPTION
**Pull request by brow86**
This fixes the wrong variable type bug (#100) and also re-works the template with the ability to add IP addresses as well.

### CODE REVIEW

**Comment by raphink** [comment]
That looks interesting. Could you add unit tests for these features, as well as for `ext_req` to qualify the bug in #100 ?

**Comment by brow86** [comment]
Sure, it'll take a little time but I'll try and get it by end-of-week.

**Comment by raphink** [comment]
@brow86 are you still interested in merging this?

**Comment by brow86** [comment]
> @brow86 are you still interested in merging this?

It would be nice to merge it in.  Was pulled off the project that involved this so never followed up.  Will try and get it tested this week as I'm off.

**Comment by raphink** [comment]
Any news @brow86 ?

**Comment by brow86** [comment]
Hey @raphink, I started to look into it and got completely sidetracked.  The delay here is due to writing a proper spec test.  Put simply, it has been so long since I have written one, I really don't remember anything around how to properly write one.  So, in short, if this is blocking a release I'd say to just pass over it for now.  Otherwise, if you or someone reading this that is willing to write in a test for me to help me get this over the finish line, it would be much appreciated.  If not, I'll try and carve out some time this weekend.

**Comment by raphink** [comment]
Hey there @brow86, I totally feel that. I've pulled my hair quite a few times with rspec, esp after taking a break from it for a while.

This is not blocking a release at the moment, take your time if you need to, I just want to make sure this needs to stay open 😁

**Comment by raphink** [comment]
@brow86 do you plan on finishing this PR?

**Comment by brow86** [comment]
> @brow86 do you plan on finishing this PR?

Won't be able to get to it this week but I am planning on taking some time off next week so should be able to resolve the conflicts/get up-to-speed on the testing frameworks then.  Sorry for the delays.

**Comment by raphink** [comment]
No problem. I just wanted to know if you were still up to it!

**Comment by mears148** [comment]
@brow86 are you still planning on fixing the spec tests so this can be merged? We are also needing this fix to move off of 1.10.0.

**Comment by brow86** [comment]
I could submit it if I had more time to figure out the integration
framework/acceptance framework as it's been years since I've written any.
Honestly, unless someone else can help me with that, then I would move
forward with the next release as this shouldn't be a blocker.

**Comment by zilchms** [comment]
hey @brow86, there were some changes to the config file management. can you take a look if your PR is still something to keep around or if all features you wanted to contriubute are properly covered? :)

**Comment by brow86** [comment]
> hey @brow86, there were some changes to the config file management. can you take a look if your PR is still something to keep around or if all features you wanted to contriubute are properly covered? :)

So it looks like this is now covered via [this line](https://github.com/voxpupuli/puppet-openssl/blob/8675b7c44c8a6db36813a8d43a8fd8e6288ef8a3/templates/cert.cnf.epp#L76) which means my original change is no longer needed.  Thanks to everyone who made that possible.

**Pull request closed without merging**
