### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
I checked and I'm fairly sure https://github.com/voxpupuli/puppet-openssl/pull/190 would be covered by the acceptance tests now. Since we're doing a major release, I'd suggest to include it now.

**Comment by bastelfreak** [comment]
@ekohl updated it

**Comment by ekohl** [comment]
As noted on IRC: should we upgrade `des3` while we're making a major version:
https://github.com/voxpupuli/puppet-openssl/blob/cac0733bc9329222ac2cc7d00ff3b10f39cf8e69/lib/puppet/provider/ssl_pkey/openssl.rb#L28

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/puppet-openssl/pull/221

**Comment by ekohl** [comment]
CI is still running, but I'd expect https://github.com/voxpupuli/puppet-openssl/pull/167 to pass.

**Review by ekohl — APPROVED** [review]
Nice! Down to 1 open PR after this.

**Pull request merged**
